services:
  - docker:dind

image: docker:latest

variables:
  IMAGE: ${IMAGE_BASE_NAME}:${CI_COMMIT_SHORT_SHA}
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_PASSWORD: ${DOCKER_PASSWORD}
  DOCKER_USER: ${DOCKER_USER}
  REGISTRY: ${REGISTRY}
 
stages:
  - prepare
  - build

check_deps:
  stage: prepare
  script:
    - docker --version
build:
  stage: build
  script:
      - echo -n "${DOCKER_PASSWORD}" | docker login -u ${DOCKER_USER} --password-stdin ${REGISTRY}
      - docker build --cache-from ${IMAGE} -t ${IMAGE} -f ./Dockerfile .
      - docker push ${IMAGE}
      - docker logout
  only:
    - master
    - add-docker-to-ci
